### PR TITLE
Refactor new linter fixes 

### PR DESCRIPTION
**Pull request by fede1608**
## Summary
- Fixed all linter errors

Note: added a comment to allow global require on `console.js` & `test/app.spec.js`

### CODE REVIEW

**Comment by raparicio6** [comment]
Great work Fede!
We have to remove the `devDependencies` we are not using any more such as `eslint-config-airbnb-base`, `eslint-config-prettier`. Also, I don't know if we are still using `babel` things. What about that? @gonziesc @mpicollo-wolox

**Comment by mpicollo-wolox** [comment]
Unused `eslint` dependencies should be removed as you mention, instead `babel` is a little bit more tricky because `mocha-chai` test framework uses that.

**Comment by raparicio6** [comment]
This pr https://github.com/Wolox/express-js-bootstrap/pull/110/ merged the same day was tested with the new linter? :thinking:

**Comment by mpicollo-wolox** [comment]
Maybe @andreaceltich could figure this out 🤔

**Pull request merged**
